env:
  browser: true
  webextensions: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules:
  no-console: "off"
  no-use-before-define: [ 1, "nofunc" ]
  import:
    extensions: false
